spring.application.name=user-service

spring.datasource.url=jdbc:h2:mem:userdb
server.port=8082


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Eureka Health Check
eureka.instance.health-check-url-path=/actuator/health
management.endpoints.web.base-path=/api/users/actuator
eureka.client.healthcheck.enabled=true

# RabbitMQ connection details
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nombre de la cola para usuarios registrados
app.rabbitmq.queue.user.registration=user-registration-queue


jwt.expiration=8000000000
jwt.secret=${SECRET_KEY}
